artifacts_root: artifacts

data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1R7bzHew6_jzoDZ2vFbQmoUxT9jiGHmZR/view?usp=sharing
  local_data_file: artifacts/data_ingestion/Data.zip
  unzip_dir: artifacts/data_ingestion